arb-dir: lib/l10n
output-dir: lib/l10n/generated
template-arb-file: markdown_editor_plus_en.arb
output-localization-file: markdown_editor_plus_localizations.dart
nullable-getter: false
use-escaping: true
synthetic-package: false
output-class: MarkdownEditorPlusLocalizations
